export enum ActionsTypes {
    FETCHING_PLAYERS_STARTED = "FETCHING_PLAYERS_STARTED",
    FETCHING_PLAYERS_FULFILLED = "FETCHING_PLAYERS_FULFILLED",
    FETCHING_PLAYERS_REJECTED = "FETCHING_PLAYERS_REJECTED"
}